server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_wishlist
    username: shivasai
    password: '1932'

  jpa:
    open-in-view: false  # Professional: Disables the warning and improves performance
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Makes Hibernate logs easy to read in your terminal

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  cache:
    type: none