spring.application.name=userregister

server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=laxmiprasanna
spring.datasource.password=thanu
spring.datasource.driver-class-name=org.postgresql.Driver
# Path to serve uploaded files
spring.web.resources.static-locations=file:uploads/profile-photos/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.redis.host=localhost
spring.redis.port=6379


# ===============================
# EMAIL CONFIGURATION (OTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mallibhai7876@gmail.com
spring.mail.password=wfkhcovkaoycstka
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Debug logs to see email sending details
spring.mail.properties.mail.debug=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
# File upload size configuration

# Multipart config
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.servlet.multipart.enabled=true
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1

app.encryption-key=1234567890123456
jwt.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyK+CayySp2/MqHhF4cCHYFYLSZwUaCYflvJCHZs1s+qjfUYk32A2SRPBq9S7FsonJvlq4bL04VlgWc/jMDN8ykSNaq8u76GOqALfc8A6twPfDiYr9WSqRBwtzDZHcTvUvYf7U+tB0S4nU/TWPPmP2I7RBFpvfQzYMe73WmWRh0UAKVYXRBTKYlqrokO3iq0qZhf0zWObx6ov0h3L7foYY5bXkQLNvDQRGk1qVC0RAvmi+L/F+oSlhQ/h3cWVueSxy4MOFc6XfzaoB0HxJEo7su1uS0Qg4sPtrSV84g5re7hXCv9cIfDzHgUSZUVDiQvq8YMe1psqBt1S6x+QsLgtjAgMBAAECggEACjVfYh8fk6fpj9E3OQpbthDNdRa4ARzor24VbdyjCop2II2AajWz2Vyf1dEEhAlNwcRpWEXKta6kz2yHpdFa/H+6YdiUDMks5LGz1zHd9XCoAYkg8JEqUjLwIgB2CgRwIe3gdv2D8hXd6Nk1N2bgvVqgWlZcSfeE4kQ4xVH2oXAOXP9sZe6cxrO7z6qEsr9JoB7Kee5HLUnyjkSaCYxLNWD69W2ENWek3GVSIpJsUTtjV6l1mJwQnAa5+1r4ZS57WQ+KwQOdXFwmVyd3Paxau8Svh9xLU2II4HxStO5SZLsPZdFfgjfXdnZt/DulWJH1oY623WaGSOWGy+wPKHPVwQKBgQDWPIEFml8tYDHZzi/MN5ZFjEsRaVHALLTCiUYPMdlJphHsm8ORjeqrSWhc4G9K4bAalxQ6yWbIKpdekM32OXAwYeos689F7/2vTIJDs/kzXPD2+UvE9T2vLOT3X127rh3YTtBygUvJRBjCYdEf7Pbs/MOzoxF+2am6nTHaAhlIoQKBgQDU54wAxMtVGdD6DKdT5U4gKGdmLwNThe88R8sVgv4nZ5C/GN6mAmn7cvaYijvsCEnIl9D5uFGuUGv4UZwFLvnQQqu+cfBMB/rh3xxKGBegI1zQaqCoHhDEISGUjeFD0ISxSrRUiN6pfN7mQO8kVLjqq8A6cp3FUk0GwdTS+a1BgwKBgAQjcxKaotALlarxcrbtM/fv99tEP5IIyw0e/b15ZwsnLB13/NUo+qmIZ32z0DKQHYjF9lwUW+nt+LKY9YGWJnaozY9EluJw+mOShMmuBlhZqUX8FtydKC3kHiAxNWxUtrrg+uHbYY1nxVqr7RBC0ZpOX7Fuqv3aUo8KTlY5yCdBAoGAahs0BTYO+Eyzf8tKoV9IvnIkhiKsD7ZScsJ9Di2IqO7Ojs7AOBA/7ZdwGrnZ/1pqG1S+S5Z27t8Z0For3dF5ozd3DKUQU3Qurt9Y4/x52c+F9EEP7Hl/dZ/lcnn7aKbFWu6WTQMhpWqcVDjMdljbB+mtFfQFeU/5H4L+pF7W4C0CgYEAytf3mGlrIIiVhC29xHFAKruwPlt6wssrV/kPDTaBQLDbr5QGm0nFz78UGpxjeKG6HuGFpH36MedIcAi4i49W0DZus3+pU7zuXG/1Tc1T7wsI6CJ6spr4q8QGkp+zx1/0amOLS2FzFAAdTmzkurWJTKcW8wWiC3Dw0FkO6EBYc/k=
jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsivgmsskqdvzKh4ReHAh2BWC0mcFGgmH5byQh2bNbPqo31GJN9gNkkTwavUuxbKJyb5auGy9OFZYFnP4zAzfMpEjWqvLu+hjqgC33PAOrcD3w4mK/VkqkQcLcw2R3E71L2H+1PrQdEuJ1P01jz5j9iO0QRab30M2DHu91plkYdFAClWF0QUymJaq6JDt4qtKmYX9M1jm8eqL9Idy+36GGOW15ECzbw0ERpNalQtEQL5ovi/xfqEpYUP4d3FlbnkscuDDhXOl382qAdB8SRKO7LtbktEIOLD7a0lfOIOa3u4Vwr/XCHw8x4FEmVFQ4kL6vGDHtabKgbdUusfkLC4LYwIDAQAB
jwt.access-token-expiration=900
jwt.refresh-token-expiration=2592000